---
- name: create users and copy file into user home dir
  hosts: all
  become: yes
  tasks:
    - name: create users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      notify: copy file    
      with_items:
        - {a: raju1,b: ram,c: /home/raju}
        - {a: rani1,b: ram,c: /tmp/rani}
  handlers:   
    - name: copy file
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd,b: /home/raju}
        - {a: /etc/group,b: /tmp/rani}
          

