---
- name: copy file from server1 to server2
  hosts: 172.31.10.166
  tasks:
    - name : fetch file from server1
      fetch:
        src: file1
        dest: /tmp
- name: copy file into server2
  hosts: 172.31.11.249
  tasks:
    - name: copy file
      copy:
        src: /tmp/172.31.10.166/file1
        dest: /tmp
... 
