---
- name: install firewalld using host scope variable
  hosts: webserver
  tasks:
    - name: install forewalld
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...
