---
- name: implementing loops
  hosts: all
  tasks:
    - name: install s/w apps
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - git 
        - tree
        - maven
...
