---
- name: install apache2
  hosts: all
  tasks:
    - name: apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: edit index.html
      copy:
        content: "wellcome to apache2"
        dest: /var/www/html/index.html
      notify: restart apache2
  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
...
