---
- name: install s/w's and unnistall
  hosts: all
  vars:
    - a: tomcat9
    - b: present
    - c: yes
  tasks:
    - name: inst/unnist
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...
