---
- name: configure tomcat
  hosts: all
  tasks:
    - name: install tomcat9 and admin
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tomcat9,b: present,c: yes}
        - {a: tomcat9-admin,b: present,c: no}
    - name: copy tomcat-user.xml
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat9
    - name: restart tomcat
      service:
        name: tomcat9
        state: restarted
    - name: pause 1 minute
      pause:
        minutes: 1
    - name: check url response of tomcat
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.10.166:9090
        - http://172.31.11.249:9090
...
