---
- name: install update uninstall
  hosts: all
  become: yes
  tasks:
    - name: in un up
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tree,b: latest,c: no}
        - {a: maven,b: latest,c: yes}
        - {a: git,b: latest,c: no}

...
